### ISSUE TITLE
Server-backend (in port 9000) exit status 2

### ISSUE THREAD

**Issue by jayflyaway** [microsoft/mouselog#5]
I tried to run the backend server via go run main.go, but got the following exception:

```
$ go run main.go
2020/02/04 13:56:51.765 [I] [parser.go:112]  generate router from comments
panic: dial tcp [::1]:3306: connectex: Der kunne ikke oprettes forbindelse, fordi destinationscomputeren aktivt nægtede det.

goroutine 1 [running]:
github.com/microsoft/mouselog/trace.(*OrmManager).open(0xc0001bc6f0)
        C:/Users/Jennifer Matthiesen/go/src/github.com/microsoft/mouselog/trace/orm_manager.go:60 +0x138
github.com/microsoft/mouselog/trace.NewOrmManager(0xafa84d, 0x5, 0xc000020920, 0x1d, 0x1d)
        C:/Users/Jennifer Matthiesen/go/src/github.com/microsoft/mouselog/trace/orm_manager.go:39 +0x84
github.com/microsoft/mouselog/trace.InitOrmManager()
        C:/Users/Jennifer Matthiesen/go/src/github.com/microsoft/mouselog/trace/orm_manager.go:14 +0x7a
main.main()
        C:/Users/Jennifer Matthiesen/go/src/mouselog/main.go:14 +0x2d
exit status 2
```

Can you help me with this?
Jennifer

**Comment by hsluoyz** [comment]
Hi @jayflyaway , Mouselog server-side requires a database (MySQL is recommended), please prepare a MySQL DB and put its connection string in app.conf: https://github.com/microsoft/mouselog/blob/master/conf/app.conf

**Comment by hsluoyz** [comment]
See: https://github.com/microsoft/mouselog#server-side

**Comment by hsluoyz** [comment]
Closed as resolved.
